FROM python:3.12‑slim as base
WORKDIR /opt/app
COPY api/requirements.txt ./
RUN pip install --no‑cache‑dir -r requirements.txt
COPY api ./api
CMD ["uvicorn", "api.app.main:app", "--host", "0.0.0.0", "--port", "8080"]
